#!/usr/bin/env python3
"""script_emit.py — emit a featuretree IR as a script that builds it natively in Fusion or SolidWorks.

The fourth and fifth backends. Unlike FreeCAD (driven headless) and Onshape (a REST API), Fusion
and SolidWorks can only be driven from inside a running copy, so the emitter writes a
self-contained script: the IR as data, the build123d reference volume after every feature, and a
small runtime in that program's own API that re-authors each feature natively (named sketches,
extrudes, cuts, revolves, fillets) and resolves the IR's face / edge QUERIES against the live body.
The script then exports a STEP and a per-feature report, and cad_verify.py checks the STEP against
the IR with the same Boolean-free IoU gate the recogniser uses.

    python script_emit.py fusion <part.ir.json> [out_dir]        # -> <part>_fusion/ script folder
    python script_emit.py solidworks <part.ir.json> [out_dir]    # -> <part>_solidworks.py (pywin32)
    python script_emit.py fusion --sample plate                   # built-in samples: plate | poly
    python script_emit.py apply <part.ir.json> <params.json> [out.ir.json]   # read edits back

Fusion: Utilities > Add-Ins > Scripts > "+" (or copy the folder into the Scripts folder), then
Run. SolidWorks: with SolidWorks open, `python <part>_solidworks.py` on Windows.
"""
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
TARGETS = HERE / "targets"
sys.path.insert(0, str(HERE))
import ir as IR  # noqa: E402

RUNTIMES = {"fusion": "fusion_runtime.py", "solidworks": "sw_runtime.py"}


def expected_volumes(spec):
    """The build123d reference volume after each feature (None where there is no solid yet, or
    for every feature if the reference build itself fails)."""
    try:
        import b3d_emit
        return b3d_emit.emit(spec)[1]["volumes"]
    except Exception as e:                   # the target may still build it; say so and go on
        print(f"  (no reference volumes: build123d could not build the IR: {e})")
        return [None] * len(spec["features"])


def script_source(target, spec, expected=None):
    if target not in RUNTIMES:
        raise ValueError(f"unknown target {target!r}; one of {sorted(RUNTIMES)}")
    if expected is None:
        expected = expected_volumes(spec)
    spec = IR.lower(spec)          # the runtimes have no ir.py: ngons and edge queries resolved here
    head = (f"# {spec['name']} — generated by featuretree script_emit.py ({target}).\n"
            "# Do not edit: change the IR and re-emit. The IR is the source of truth.\n"
            "import json\n\n"
            f"SPEC = json.loads({json.dumps(spec)!r})\n"
            f"EXPECTED = {expected!r}  # build123d volume (mm^3) after each feature\n\n")
    return head + (TARGETS / "_geom.py").read_text() + "\n\n" + (TARGETS / RUNTIMES[target]).read_text()


def emit(target, spec, out_dir):
    """Write the script(s) for `target` into out_dir; return the main script path."""
    out_dir = Path(out_dir)
    src = script_source(target, spec)
    (out_dir).mkdir(parents=True, exist_ok=True)
    (out_dir / f"{spec['name']}.ir.json").write_text(json.dumps(spec, indent=1))
    if target == "solidworks":
        path = out_dir / f"{spec['name']}_solidworks.py"
        path.write_text(src)
        return path
    # Fusion runs a script from a folder holding <folder>.py + <folder>.manifest
    name = f"{spec['name']}_fusion"
    folder = out_dir / name
    folder.mkdir(exist_ok=True)
    (folder / f"{name}.py").write_text(src)
    (folder / f"{name}.manifest").write_text(json.dumps(_manifest(f"featuretree: build {spec['name']}")))
    reader = out_dir / "featuretree_fusion_read"
    reader.mkdir(exist_ok=True)
    (reader / "featuretree_fusion_read.py").write_text((TARGETS / "fusion_read.py").read_text())
    (reader / "featuretree_fusion_read.manifest").write_text(
        json.dumps(_manifest("featuretree: read parameters back to the IR")))
    return folder / f"{name}.py"


def _manifest(desc):
    return {"autodeskProduct": "Fusion360", "type": "script", "author": "featuretree",
            "description": {"": desc}, "supportedOS": "windows|mac", "editEnabled": True}


def main():
    a = sys.argv[1:]
    if len(a) < 2:
        print(__doc__)
        return 0
    if a[0] == "apply":
        spec = json.loads(Path(a[1]).read_text())
        IR.update_from_params(spec, json.loads(Path(a[2]).read_text()))
        out = Path(a[3]) if len(a) > 3 else Path(a[1])
        out.write_text(json.dumps(spec, indent=1))
        print(f"updated {out}")
        return 0
    target = a[0]
    if a[1] == "--sample":
        spec = IR.SAMPLES[a[2] if len(a) > 2 else "plate"]()
        out_dir = HERE / "out" / target
    else:
        spec = json.loads(Path(a[1]).read_text())
        out_dir = Path(a[2]) if len(a) > 2 else Path(a[1]).parent
    path = emit(target, spec, out_dir)
    print(f"emitted {path}  ({len(spec['features'])} features, target {target})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
