#!/usr/bin/env python3
"""native_nist.py — NIST's native SolidWorks test parts through two decoders, plus designer trees.

NIST publishes the CTC/FTC test parts as native CAD files as well as STEP. This measures:
  1. geometry: each .SLDPRT decoded to STEP by cadmpeg (open source) and by Onshape (commercial
     translators), each compared with NIST's own AP203 geometry STEP of the part (volume + a
     Boolean-free IoU; a registered IoU too when the same-frame one is below 99%);
  2. trees: the designer's feature tree as cadmpeg decodes it from the .SLDPRT (solid-modifying
     operations only), against the number of operations in featuretree's recovered tree.

Inputs (not in the repo):
  NIST_NATIVE  dir of the eleven *_sw1802.SLDPRT files, from
               https://www.nist.gov/document/nist-ftc-ctc-pmi-cad-models (the zip's "SolidWorks MBD 2018")
               default ~/Downloads/nist-native/sw
  NIST_STEP    NIST's "AP203 geometry only" STEP dir, default ~/Downloads/NIST-PMI-STEP-Files/AP203 geometry only
Tools: cadmpeg on PATH; Onshape keys (see onshape_client.py). Decoded STEPs, dumps and the IoU
results are cached next to the .SLDPRT files; --fresh recomputes the IoUs.

    python3 paper/figures/native_nist.py            # -> paper/figures/native_nist.{json,md}
"""
import json
import os
import re
import subprocess
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))
NATIVE = Path(os.environ.get("NIST_NATIVE", Path.home() / "Downloads/nist-native/sw"))
STEP = Path(os.environ.get("NIST_STEP", Path.home() / "Downloads/NIST-PMI-STEP-Files/AP203 geometry only"))
OUT = Path(__file__).resolve().parent
SOLID_OPS = {"extrude", "revolve", "hole", "fillet", "chamfer", "draft", "pattern", "shell", "sweep",
             "loft", "mirror", "combine", "rib"}


def key(p):
    return re.match(r"(nist_[cf]tc_\d\d)", Path(p).name).group(1)


def decode(f):
    cm = f.with_suffix(f.suffix + ".cadmpeg.step")
    if not cm.exists():
        subprocess.run(["cadmpeg", "convert", str(f), "-o", str(cm), "--allow-errors"], capture_output=True)
    dump = f.with_suffix(f.suffix + ".cadir.json")
    if not dump.exists():
        subprocess.run(["cadmpeg", "dump", str(f), "-o", str(dump)], capture_output=True)
    osh = f.with_suffix(f.suffix + ".onshape.step")
    if not osh.exists():
        import onshape_translate
        onshape_translate.translate(f, osh)
    return {"cadmpeg": cm, "onshape": osh}, dump


def compare(ref, step):
    from build123d import import_step

    from iou_check import iou, registered_iou, solid_part
    a, b = solid_part(import_step(str(ref))), solid_part(import_step(str(step)))
    solids = b.solids() if hasattr(b, "solids") else [b]
    row = {"dvol_pct": round(100 * (b.volume - a.volume) / a.volume, 3),
           "valid": all(s.is_valid() for s in solids), "faces": len(b.faces())}
    p, _ = iou(a, b, n=8000)
    row["iou_pct"] = round(100 * p, 2)
    if p < 0.99:
        row["iou_registered_pct"] = round(100 * registered_iou(a, b, n=8000, n_search=1500)["iou"], 2)
    return row


def main():
    fresh = "--fresh" in sys.argv
    cache = NATIVE / "native_nist.iou.json"
    geo = {} if fresh or not cache.exists() else json.loads(cache.read_text())
    rows = []
    for f in sorted(NATIVE.glob("*.SLDPRT")):
        k = key(f)
        steps, dump = decode(f)
        ref = next(STEP.glob(k + "*.stp"))
        for dec, st in steps.items():
            if f"{k}:{dec}" not in geo:
                geo[f"{k}:{dec}"] = compare(ref, st)
                cache.write_text(json.dumps(geo, indent=1))
        feats = json.loads(dump.read_text())["model"].get("features", [])
        ops = Counter(d for d in (x["definition"].get("definition") for x in feats) if d in SOLID_OPS)
        rec = next((ROOT / "paper/figures/recovered").glob(k + "*.stp.json"))
        ours = sum(1 for x in json.loads(rec.read_text())["spec"]["features"] if x["kind"] != "sketch")
        rows.append({"part": k, "cadmpeg": geo[f"{k}:cadmpeg"], "onshape": geo[f"{k}:onshape"],
                     "designer_ops": sum(ops.values()), "designer_mix": dict(ops), "ours_ops": ours})
    ok = lambda r: r["iou_pct"] >= 99.5 and abs(r["dvol_pct"]) <= 0.5   # noqa: E731
    summary = {d: sum(ok(r[d]) for r in rows) for d in ("cadmpeg", "onshape")}
    (OUT / "native_nist.json").write_text(json.dumps({"summary": summary, "parts": rows}, indent=1))

    md = ["# NIST native SolidWorks parts: two decoders, and the designer's tree", "",
          "Generated by `paper/figures/native_nist.py`. Reference geometry: NIST's AP203 geometry-only STEP "
          "of each part. A decoder matches when IoU >= 99.5% and |dV| <= 0.5%.", "",
          f"**Onshape: {summary['onshape']}/{len(rows)} match. cadmpeg: {summary['cadmpeg']}/{len(rows)} match.**", "",
          "| part | Onshape IoU | Onshape dV | cadmpeg IoU | cadmpeg dV | cadmpeg solid valid | designer ops | featuretree ops |",
          "|---|---|---|---|---|---|---|---|"]
    for r in rows:
        o, c = r["onshape"], r["cadmpeg"]
        md.append(f"| {r['part']} | {o['iou_pct']}% | {o['dvol_pct']}% | {c['iou_pct']}% | {c['dvol_pct']}% | "
                  f"{'yes' if c['valid'] else 'no'} | {r['designer_ops']} | {r['ours_ops']} |")
    md += ["", "Designer ops: solid-modifying features in the designer's tree as cadmpeg decodes it "
           "(extrude, revolve, hole, fillet, chamfer, draft, pattern, shell, rib, combine). featuretree ops: "
           "non-sketch features in the tree featuretree recovers from NIST's STEP (paper/figures/recovered/). "
           "One designer hole or pattern feature stands for many of our cuts, which is most of the gap on the CTC parts."]
    (OUT / "native_nist.md").write_text("\n".join(md) + "\n")
    print("\n".join(md))


if __name__ == "__main__":
    main()
